version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: dior-3-front-dev
    ports:
      - "9300:9300"
    environment:
      - NODE_ENV=development
      - VITE_HOST=0.0.0.0
      - HUSKY=0
      - HUSKY_SKIP_INSTALL=1
    volumes:
      - ./:/app
      - /app/node_modules
    command: pnpm run dev
    restart: unless-stopped
